### PR TITLE
SPNEGO token validation

### PR DESCRIPTION
**Pull request by antoniobusrod**
To allow SPNEGO token validation, `Negotiate` instead of `Token`

### CODE REVIEW

**Comment by antoniobusrod** [comment]
When authenticate fails, set status code (default to 401) and
WWW-Authenticate header with custom message (e.g. Negotiate),
for SPNEGO token validation process

**Comment by peralmq** [comment]
Hi @antoniobusrod, this looks good. Please add a test that describes the requirements for SPNEGO support. Then I'm happy to merge it.

**Comment by peralmq** [comment]
@antoniobusrod see my comment please or I'm gonna close this.

**Comment by antoniobusrod** [comment]
Hi Pelle, I will submit the unit tests ASAP. Thanks for the reminder.

**Comment by peralmq** [comment]
:+1:

**Comment by peralmq** [comment]
Darn.. sorry @antoniobusrod.. missed your test commit. Merging and publishing this soon. Thanks for the help!

**Pull request merged**
